import type {Metadata} from "next";
import "../styles/globals.css";
import "../styles/font.css"
import "../styles/mgpd.css"
import "../styles/common.css"
import {StoreProvider} from "@/src/provider/store-provider";
import React from "react";

export const metadata: Metadata = {
    title: "Glee",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests"/>
        <body>
        <StoreProvider>
            <div className="body--wrap">
                {children}
            </div>
        </StoreProvider>
        </body>
        </html>
    );
}
