import type {Metadata} from "next";
import "./globals.css";
import Header from "@/src/components/Header";
import StyledComponentsRegistry from "@/src/lib/registry";
import {StoreProvider} from "@/src/provider/store-provider";

export const metadata: Metadata = {
    title: "Glee",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <StoreProvider>
            <StyledComponentsRegistry>
                <div className="wrapper">
                    <Header/>
                    <div>
                        {children}
                    </div>
                </div>
            </StyledComponentsRegistry>
        </StoreProvider>
        </body>
        </html>
    );
}
